---
language: c

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y debootstrap syslinux time
  - sudo make -C live-build install

script:
  - make binary.hybrid.iso

deploy:
  edge: true
  provider: releases
  api-key:
    - secure: "RDp9Y4gqzQ3sEfLFW7O5pWU3D0VQD70H7/YBKYWiCSoKd1HF6yoe9RKtEXCyruCW5zFCcsEuFIrV3QKtoV9jhFutAFFXOo4yzwChhRyLeV6CEbhTynw8IV436d3tWZFbIxAqa7yQmeGEVhaArsDByWsxypr5VwolvpIVSiUXPV8="
  file: binary.hybrid.iso
  on:
    tags: true
    all_branches: true
