---
language: c

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y debootstrap syslinux time
  - sudo make -C live-build install

script:
  - make

#deploy:
#  edge: true
#  provider: releases
#  api-key:
#    - secure: <encrypted GitHub oauth token with repo or repo:public permission>
#  file: binary.hybrid.iso
#  on:
#    tags: true
#    all_branches: true
