---
language: c

before_install:
  - sudo apt-get update -qq
  - apt-cache search live-build

install:
  - sudo make -C live-build install
  - which lb
  - lb --version
  - sudo apt-get install -y debootstrap syslinux time
  - which lb
  - lb --version

script:
  - which lb
  - lb --version
  - make

#deploy:
#  edge: true
#  provider: releases
#  api-key:
#    - secure: <encrypted GitHub oauth token with repo or repo:public permission>
#  file: binary.hybrid.iso
#  on:
#    tags: true
#    all_branches: true
