#!/bin/sh

usage()
{
    tbox-init-drive DEVICE
}

create_shares()
{
    MNT=$1

    mkdir -p "$MNT/Memories"
    mkdir -p "$MNT/Backups"
    mkdir -p "$MNT/Downloads"
    mkdir -p "$MNT/Movies"
    mkdir -p "$MNT/TV Shows"
}

setup_permissions()
{
    MNT=$1

# for now give everyone permissions for everything
    chown -R nobody:nogroup $MNT/*
    find $MNT/* -type d -print0 | xargs -0 chmod 777 
    find $MNT/* -type f -print0 | xargs -0 chmod 666
}

persist_config()
{
    MNT=$1
    SIZE=$2

    if [ -f $MNT/persistence ]; then
        return
    fi

    truncate -s $SIZE $MNT/persistence
    mkfs.ext4 -F -L tbox-config $MNT/persistence

    MNTPNT=$(mktemp -d)
    mount -t ext4 $MNT/persistence $MNTPNT
    echo "/etc union" > $MNTPNT/persistence.conf
    sync
    umount $MNTPNT
    rmdir $MNTPNT
}


if [ "$(id -u)" != "0" ]; then
  clear
  echo "#########################################################"
  echo "# please execute with 'sudo' or -DANGEROUS!!!- as root  #"
  echo "# example: sudo tbox-init-drive <drive>                 #"
  echo "#########################################################"
  exit 1
fi

DEV=$1

if [ -z "$DEV" ]; then
    usage
    exit 1
fi

SHARE=/shares

echo "claiming drive"
e2label $DEV tbox-shares

echo "ensuring drive is mounted"
sudo mount $SHARE

echo "create shares"
create_shares $SHARE

echo "configuring permissions"
setup_permissions $SHARE

echo "configuring persistence"
persist_config $SHARE 128M

echo "reboot, for config changes to be saved"
echo "e.g. sudo reboot"
