#!/bin/sh

create_filesystem()
{
    DEV=$1
    sudo mkfs.ext4 -L tbox-shares $DEV
}


if [ "$(id -u)" != "0" ]; then
  clear
  echo "#########################################################"
  echo "# please execute with 'sudo' or -DANGEROUS!!!- as root  #"
  echo "# example: sudo tbox-format-drive <drive>               #"
  echo "#########################################################"
  exit 1
fi

VENDOR=$(cat /sys/block/$DISK/device/vendor):
MODEL=$(cat /sys/block/$DISK/device/model):

clear
echo "*** DANGER DANGER **"
echo -n "Erase ALL DATA from $VENDOR $MODEL ($DEV)? [y/N]"
read CONFIRM

if [ "$CONFIRM" != "y" ]; then
    echo "aborting.."
    exit 0
fi

echo "setting up filesystem"
create_filesystem $1

/usr/sbin/tbox-init-drive
