---
- name: Sync Config
  hosts: treasurebox
  user: user
  sudo: yes
  tasks:
    - synchronize: src=../config/includes.chroot/etc/ dest=/etc
    - synchronize: src=../config/includes.chroot/usr/ dest=/usr
    - synchronize: src=../config/includes.chroot/srv/ dest=/srv
